server:
  port: 8080

spring:
  application:
    name: vmall-backend
  datasource:
    url: jdbc:mysql://localhost:3306/vmall?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: "1314"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
